name: Page Speed Insights Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Running on Index Page
        uses: jakepartusch/psi-action@v1.3
        id: psi
        with:
          url: "https://olis.tech/"
          threshold: 100
          strategy: mobile
          key: ${{ secrets.PAGESPEED }}
